# Generated by Django 2.2 on 2020-06-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='update',
            new_name='updated',
        ),
    ]
